### PR TITLE
Svgs

### PR DESCRIPTION
**Pull request by paulbuis**
Added .svg files in svg directory.
Added links to svg files in proposal.md

### CODE REVIEW

**Comment by doctor-g** [comment]
I don't think we should maintain html and md versions of the spec; I think we should have only one authoritative copy here in the repo. We can always add a build script if we need to automate production of other versions.

In that vein, I think it makes more sense to automate the creation of the diagrams rather than include generated ones, since generated ones need to be manually regenerated with each change to the spec. 

So, it seems to me like either we should automate the process or not do it at all yet lest the spec and the diagrams get quickly out of sync.

**Comment by paulbuis** [comment]
I thought I deleted the HTML file from things before attempting the pull request. Sorry, that was just a preview copy from my laptop.

Automating it makes sense, but we'd still need both the .dot and the .svg on GitHub to make the SVG files viewable from the GitHub. The .svgs were generated by running "dot xyz.dot -Tsvg -O"

I suppose I could put the .dot files in the svg directory along with a Makefile.

The problem is I don't think I can generate the .dot files from proposal.md.

**Comment by doctor-g** [comment]
It also strikes me, now that I think about it, that these will have to change both structurally and in terms of name once Huseyin puts in his notes about an extracted SE course. (I cannot tag him yet because he hasn't joined up on the repo, and I don't know his github name. :/ )
Maybe we just close this one until we hear from him. Sound OK to you?

**Comment by paulbuis** [comment]
Yes, just reject this PR.

My current solution is just to set up a separate repository for the SVGs that will be trailing the text of the proposal in your repository. Right now it is inline SVG in the HTML because that is the only way I could figure out right now for how to get the scaling to work smoothly. Previously, I had used JavaScript to re-write the SVG to yank out the height and width attributes that dot generates.

See: https://paulbuis.github.io/cs_curriculum/index.html

**Pull request closed without merging**
