### PR TITLE
CS322 introduced

### PR DESCRIPTION
**Pull request by hergin**

### CODE REVIEW

**Comment by doctor-g** [comment]
300 is an old course number, so we have to pick a new one. How about something like 322 (222+100) or 398 (498-100)? 

@paulbuis do you have an opinion here?

**Comment by hergin** [comment]
I didnt see the 300 in the catalog but I am ok with any number.

**Comment by doctor-g** [comment]
It's not there now, but there was such a course, and I believe we still cannot reuse numbers from old courses.

**Comment by doctor-g** [comment]
@hergin were you going to update the number? There are other aspects of this to consider as well, such as the total number of credit hours and the assessment plans. We should also have a subsection explaining the content and purpose of the course, like I have for 390 below.

**Comment by hergin** [comment]
I updated the numbers. I added some section like 390 as well. I think it should be fine for discussion starter.

**Pull request merged**
