### PR TITLE
Adding required stats & lab science

### PR DESCRIPTION
**Pull request by paulbuis**
Added specific stats and lab science courses to the core

### CODE REVIEW

**Comment by paulbuis** [comment]
This is my first GitHub pull request using branches (ever)!

**Comment by doctor-g** [comment]
Excellent, thanks! I wanted to do this but didn't get around to it. I'm glad you were willing to put in the work!

**Comment by paulbuis** [comment]
Here is a list of electives in the format I used earlier, each with the concentrations they are required on.

The requirement in Banner is that each concentration must enumerate all electives separately from the electives on the others. So where you have "Any CS course numbered over 300," we will eventually need to specifically list the electives that are not required on that concentration. For now, I didn't want to clutter the proposal and wanted to look at what programs each course was a part of.

Again, I hope this is useful, but I don't know quite what to do with it.

**Comment by doctor-g** [comment]
Sorry, I am not sure what "here" is here.

**Comment by paulbuis** [comment]
I didn't intend for this to go to GitHub, I thought I was sending ordinary e-mail with an attachment.

**Pull request merged**
